name: Update CSV from Google Sheets

on:
  schedule:
    - cron: "0 * * * *"  # Runs at minute 0 of every hour
  workflow_dispatch: # Also allows manual trigger if needed

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch CSV
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/YOUR_SHEET_ID/pub?gid=YOUR_GID&single=true&output=csv" -o data/data.csv

      - name: Commit and Push Updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/data.csv
          git commit -m "Update CSV from Google Sheets"
          git push
