name: Update CSV from Google Sheets

on:
  schedule:
    - cron: "0 * * * *"  # Runs at the top of every hour
  workflow_dispatch:     # Allows manual trigger if needed

permissions:
  contents: write        # Grants the workflow permission to push changes

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch CSV
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTdfofqx68BuFHAnCLFUiH9H1VyHM6TvkYJl3gXOWhv9oq_wrh3D8ffgWlnwCCyvHb6Sb5dfHT8sftr/pub?gid=576642623&single=true&output=csv" -o data/data.csv

      - name: Commit and Push Updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/data.csv

          # Check if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit. Exiting."
          else
            git commit -m "Update CSV from Google Sheets"
            git push
          fi
